#ifndef AVD_REGS_H_
#define AVD_REGS_H_

#define AVD_REG_POWER_ON	0x1000000

#define AVD_REG_RUN_CTRL	0x08
#define AVD_RUN_CTRL_UNK_RUN	BIT(0)
#define AVD_RUN_CTRL_UNK_STOP	BIT(1) | BIT(2) | BIT(3)

#define AVD_REG_MBOX_IRQ_ENABLE	0x48
#define AVD_REG_MBOX_IRQ_CLR	0x4c
#define AVD_MBOX0_EMPTY	BIT(0)
#define AVD_MBOX0_NOT_EMPTY	BIT(1)
#define AVD_MBOX1_EMPTY	BIT(2)
#define AVD_MBOX1_NOT_EMPTY	BIT(3)

#define AVD_REG_MBOX0_STATUS	0x50
#define AVD_REG_MBOX0_SUBMIT	0x54
#define AVD_REG_MBOX0_RETRIEVE	0x58
#define AVD_REG_MBOX1_STATUS	0x5c
#define AVD_REG_MBOX1_SUBMIT	0x60
#define AVD_REG_MBOX1_RETRIEVE	0x64
#define AVD_MBOX_ENABLE	BIT(0)

#define AVD_REG_FLAG0_SET	0x90
#define AVD_REG_FLAG1_SET	0x94
#define AVD_REG_FLAG0_CLR	0x98
#define AVD_REG_FLAG1_CLR	0x9c

#endif /* AVD_REGS_H_ */
